language: node_js
node_js:
  - "lts/*"

before_script:
  - npm install

script:
  - npm run prod

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change   

deploy:
  local-dir: dist/angular
  provider: pages
  skip-cleanup: true
  github-token: 7181f6c8e43ef822987d131c641767d649766546   # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    all_branches: true