language: node_js
node_js:
  - "lts/*"

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change   